# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Inevitable (Update Staging Branch )

on:
  push:
    branches: [ "main" ]

jobs:
  update-staging-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - run: git checkout staging
    - run: git merge main
    - run: git push origin staging
 
